import { LightningElement } from 'lwc';
import greater from 'c/lwc_Greaterof3numbers';

describe('c-lwc-greaterof3-numbers', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-greaterof3-numbers', {
            is: Lwc_Greaterof3numbers
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});